### ISSUE TITLE
How to clean the json

### ISSUE THREAD

**Issue by alfamejl** [olejorgenb/ColorNote-backup-decryptor#9]
Hi,

Thank you for the script!

I got a json converted. I have not yet managed to clean it up. It says that fixup-v1 or fixup-v2 are not recognized as internal or external commands, operable programs or batch files.

```
C:\Users\erikp\ColorNote-backup-decryptor-master\ColorNote-backup-decryptor-master>java -jar colornote-decrypt.jar 0000 28 < colornote-20231114.backup | fixup-v2 > notes.json
'fixup-v2' is not recognized as an internal or external command,
operable program or batch file.
```

Any idea on how to solve it? 
Bless you

**Comment by olejorgenb** [comment]
Looks like you're on Windows. 

These scripts are written for linux shells, so it will not work out-of the box on windows. You can try to install cygwin (or gitbash (which is built on cygwin I think, but offers a possible easier to install package)

If you do, try to run this instead since `.` is probably not in `PATH` by default in cygwin.
```
java -jar colornote-decrypt.jar 0000 28 < colornote-20231114.backup | ./fixup-v2 > notes.json
```

You could also look into the open PR which tries to improve the UX of some of these, but I don't remember if that is any easier to run on windows or not. (I think maybe it replaced some of the scripts with a clojure/java implementation so maybe)

**Comment by alfamejl** [comment]
Praise Jesus!
It works well. Thank you. After some tries at installing cygwin and perl it worked perfectly.
Thanks and bless you very much through the Lord of all creation.
